const stations = [
    {file:"01_BatInWar.mp3", title:"1. The Bat in the War"},
    {file:"02_BearChipmunk.mp3", title:"2. The Bear and the Chipmunk"},
    {file:"03_BearTwoFriends.mp3", title:"3. The Bear and the Two Friends"},
    {file:"04_BoyRattlesnake.mp3", title:"4. The Boy and the Rattlesnake"},
    {file:"05_ButterflyMonk.mp3", title:"5. The Butterfly and the Kind Monk"},
    {file:"06_CamelThistle.mp3", title:"6. The Camel and the Thistle"},
    {file:"07_CamelTent.mp3", title:"7. The Camel in the Tent", image: "The Camel and the Tent.png"},
    {file:"08_CatFox.mp3", title:"8. The Cat and the Fox"},
    {file:"09_CrowPeacock.mp3", title:"9. The Crow and the Peacock", image: "The Crow and the Peacock Feathers.png"},
    {file:"10_DeerAntlers.mp3", title:"10. The Deer and His Antlers"},
    {file:"11_DogReflection.mp3", title:"11. The Dog and His Reflection"},
    {file:"12_DogWolf.mp3", title:"12. The Dog and the Wolf"},
    {file:"13_DogManger.mp3", title:"13. The Dog in the Manger"},
    {file:"14_DonkeyLapdog.mp3", title:"14. The Donkey and the Lapdog"},
    {file:"15_DonkeySalt.mp3", title:"15. The Donkey and the Salt"},
    {file:"16_EagleArrow.mp3", title:"16. The Eagle and the Arrow"},
    {file:"17_EagleBeetle.mp3", title:"17. The Eagle and the Beetle"},
    {file:"18_EagleChicken.mp3", title:"18. The Eagle Who Thought He Was a Chicken"},
    {file:"19_ElephantRope.mp3", title:"19. The Elephant and the Rope"},
    {file:"20_FalconKing.mp3", title:"20. The Falcon and the King"},
    {file:"21_FoxStork.mp3", title:"21. The Fox and the Stork"},
    {file:"22_FoxTraitorRooster.mp3", title:"22. The Fox and the Traitor Rooster"},
    {file:"23_FrogsWantedKing.mp3", title:"23. The Frogs Who Wanted a King"},
    {file:"24_GooseGoldenEggs.mp3", title:"24. The Goose and the Golden Eggs"},
    {file:"25_HeronFish.mp3", title:"25. The Heron and the Fish"},
    {file:"26_HorseLoadedDonkey.mp3", title:"26. The Horse and the Loaded Donkey"},
    {file:"27_HorseStagRider.mp3", title:"27. The Horse, the Stag, and the Rider"},
    {file:"28_LazySwallow.mp3", title:"28. The Lazy Swallow and the Winter"},
    {file:"29_LionCleverRabbit.mp3", title:"29. The Lion and the Clever Rabbit"},
    {file:"30_LionMouse.mp3", title:"30. The Lion and the Mouse"},
    {file:"31_LionPainting.mp3", title:"31. The Lion and the Painting"},
    {file:"32_LionDonkeyFox.mp3", title:"32. The Lion, the Donkey, and the Fox"},
    {file:"33_LionsDividedHerd.mp3", title:"33. The Lions and the Divided Herd"},
    {file:"34_LittleBirdCow.mp3", title:"34. The Little Bird and the Cow"},
    {file:"35_MiceWantedBell.mp3", title:"35. The Mice Who Wanted a Bell"},
    {file:"36_MonkeyCrocodile.mp3", title:"36. The Monkey and the Crocodile"},
    {file:"37_MouseFrogHawk.mp3", title:"37. The Mouse, the Frog, and the Hawk"},
    {file:"38_NightingaleHawk.mp3", title:"38. The Nightingale and the Hawk"},
    {file:"39_OakTreeReed.mp3", title:"39. The Oak Tree and the Reed"},
    {file:"40_OldDogHole.mp3", title:"40. The Old Dog and the Hole"},
    {file:"41_OldLionFootprints.mp3", title:"41. The Old Lion and the Footprints"},
    {file:"42_OldManScorpion.mp3", title:"42. The Old Man and the Scorpion"},
    {file:"43_PeacockCrane.mp3", title:"43. The Peacock and the Crane"},
    {file:"44_WomanMongoose.mp3", title:"44. The Peasant Woman and the Mongoose"},
    {file:"45_PeasantSnake.mp3", title:"45. The Peasant and the Snake"},
    {file:"46_ScorpionFrog.mp3", title:"46. The Scorpion and the Frog"},
    {file:"47_ElephantNoise.mp3", title:"47. The Silent Elephant and the Noise"},
    {file:"48_SnakeFile.mp3", title:"48. The Snake and the Steel File"},
    {file:"49_SpiderFly.mp3", title:"49. The Spider and the Flattered Fly"},
    {file:"50_TigerFox.mp3", title:"50. The Tiger and the Smart Fox"},
    {file:"51_TigerWoodpecker.mp3", title:"51. The Tiger and the Woodpecker"},
    {file:"52_TurtleScorpion.mp3", title:"52. The Turtle and the Scorpion"},
    {file:"53_TurtleGeese.mp3", title:"53. The Turtle and the Two Geese"},
    {file:"54_TwoDogs.mp3", title:"54. The Two Dogs"},
    {file:"55_TwoFrogsMilk.mp3", title:"55. The Two Frogs and the Milk"},
    {file:"56_RoostersEagle.mp3", title:"56. The Two Roosters and the Eagle"},
    {file:"57_TwoSeeds.mp3", title:"57. The Two Seeds"},
    {file:"58_WarriorWolf.mp3", title:"58. The Warrior and the Loyal Wolf"},
    {file:"59_WolfLamb.mp3", title:"59. The Wolf and the Lamb"},
    {file:"60_WolfSheep.mp3", title:"60. The Wolf in Sheep’s Clothing", image: "The Wolf in Sheep's Clothing.png"},
    {file:"61_WoodcutterTrees.mp3", title:"61. The Woodcutter and the Trees"}
];

const lessonData = {};

lessonData["01_BatInWar.mp3"] = [{
    text: "The Bat in the War. A long time ago, a terrible war started between the flying birds and the walking beasts. The clever bat knew nothing of which side to choose. He only wanted to be safe. When the birds were winning the battle, the bat flew to their leader. He said, 'Look at my long wings! I am a bird. I will fight with you.' But the next day, the strong beasts were winning. The bat walked on the ground and said, 'Look at my sharp teeth and brown fur! I am a beast. I am on your side.' Finally, the long war ended, and there was peace in the forest. Both sides organized a meeting. They remembered the bat's selfish trick. Because he was loyal to nobody, nobody wanted to be his friend. The sad bat had to hide in dark caves forever.",
    dict: { "terrible": "korkunç", "started": "başladı", "between": "arasında", "beasts": "canavarlar/hayvanlar", "clever": "zeki", "choose": "seçmek", "winning": "kazanıyor", "battle": "savaş", "leader": "lider", "wings": "kanatlar", "fight": "savaşmak", "ground": "yer/zemin", "sharp": "keskin", "teeth": "dişler", "brown": "kahverengi", "fur": "kürk", "Finally": "sonunda", "ended": "bitti", "peace": "barış", "organized": "organize etti", "meeting": "toplantı", "remembered": "hatırladı", "selfish": "bencil", "trick": "hile/tuzak", "loyal": "sadık", "nobody": "hiç kimse", "friend": "arkadaş", "hide": "saklanmak", "dark": "karanlık", "caves": "mağaralar" },
    questions: [ {q:"Did the clever bat know which side to choose at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did he want to be safe?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he say he was a bird when the birds were winning?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he loyal to many friends?", a_en:"No", a_tr:"Hayır"}, {q:"Did both sides remember his selfish trick?", a_en:"Yes", a_tr:"Evet"}, {q:"Did nobody want to be his friend?", a_en:"Yes", a_tr:"Evet"}, {q:"Does he hide in dark caves forever?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_BearChipmunk.mp3"] = [{
    text: "The Bear and the Chipmunk. A long time ago, a huge, proud bear was walking in the green forest. He felt very important and boastful. He shouted loudly, 'I am the strongest animal in the world! I can do absolutely anything!' A tiny chipmunk heard him and asked, 'Can you really stop the sun from coming up in the morning?' The arrogant bear said, 'Yes, I certainly can!' The bear sat down facing the east and commanded, 'The sun will not rise today!' But the next morning, the bright sun came up as usual. The little chipmunk started to laugh. He jumped around and sang, 'The big bear is wrong! He is not the strongest!' He laughed very hard at the embarrassed bear. The bear became furious, swung his heavy paw, and scratched the chipmunk's back.",
    dict: { "huge": "kocaman", "proud": "gururlu", "forest": "orman", "felt": "hissetti", "important": "önemli", "boastful": "böbürlenen", "shouted": "bağırdı", "loudly": "yüksek sesle", "strongest": "en güçlü", "world": "dünya", "absolutely": "kesinlikle", "anything": "herhangi bir şey", "tiny": "küçücük", "chipmunk": "sincap", "heard": "duydu", "really": "gerçekten", "stop": "durdurmak", "morning": "sabah", "arrogant": "kibirli", "certainly": "kesinlikle", "facing": "dönük", "east": "doğu", "commanded": "emretti", "rise": "doğmak/yükselmek", "bright": "parlak", "as usual": "her zamanki gibi", "laugh": "gülmek", "jumped": "zıpladı", "around": "etrafında", "wrong": "yanlış", "embarrassed": "utanmış", "furious": "öfkeli", "swung": "salladı", "heavy": "ağır", "paw": "pençe", "scratched": "tırmaladı" },
    questions: [ {q:"Was the bear very humble?", a_en:"No", a_tr:"Hayır"}, {q:"Did the bear say he could do anything?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the sun stop rising because the bear commanded it?", a_en:"No", a_tr:"Hayır"}, {q:"Did the chipmunk laugh at the bear?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the bear embarrassed?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bear become furious?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bear scratch the chipmunk's back?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_BearTwoFriends.mp3"] = [{
    text: "The Bear and the Two Friends. Two good friends were walking together through a dark, quiet forest. Suddenly, a huge, hungry bear appeared on the path. One friend panicked, ran away quickly, climbed a tall tree, and hid among the leaves. The other friend could run at no great speed. He fell to the ground and pretended to be completely dead. He knew that bears usually eat no dead animals. The heavy bear came very close, smelled the man's hair and ears, and then walked away slowly. After the danger passed, the friend in the tree safely came down. He smiled and asked, 'What did the big bear whisper in your ear?' The man brushed the dirt off his clothes and replied, 'He told me never to travel with a friend who leaves me alone in danger.'",
    dict: { "together": "birlikte", "quiet": "sessiz", "Suddenly": "aniden", "appeared": "göründü", "path": "yol", "panicked": "panikledi", "ran away": "kaçtı", "quickly": "hızlıca", "climbed": "tırmandı", "leaves": "yapraklar", "ground": "yer", "pretended": "numara yaptı", "completely": "tamamen", "dead": "ölü", "knew": "biliyordu", "usually": "genellikle", "close": "yakın", "smelled": "kokladı", "danger": "tehlike", "passed": "geçti", "safely": "güvenli bir şekilde", "whisper": "fısıldamak", "brushed": "fırçaladı", "dirt": "kir/toz", "replied": "cevap verdi" },
    questions: [ {q:"Did a hungry bear appear on the path?", a_en:"Yes", a_tr:"Evet"}, {q:"Did both friends climb the tree?", a_en:"No", a_tr:"Hayır"}, {q:"Did the second friend pretend to be dead?", a_en:"Yes", a_tr:"Evet"}, {q:"Do bears usually eat dead animals?", a_en:"No", a_tr:"Hayır"}, {q:"Did the bear smell the man's ears?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bear kill the man on the ground?", a_en:"No", a_tr:"Hayır"}, {q:"Should you travel with friends who leave you in danger?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["04_BoyRattlesnake.mp3"] = [{
    text: "The Boy and the Rattlesnake. A young boy was walking alone in the cold, snowy mountains. Suddenly, he saw a rattlesnake on the frozen ground. The snake was freezing and almost dead. The snake looked up and begged, 'Please, little boy, I am so cold. Put me under your warm winter jacket and take me down the mountain, or I will certainly die.' The boy stepped back and said, 'No! You are a dangerous rattlesnake. If I pick you up, you will bite me and I will die.' The snake promised, 'I will bite you at no time. You are saving my life. I will be good.' The boy felt sorry for the poor animal. He put the snake safely inside his jacket and walked down the mountain. When they reached the warm valley, the boy put the snake on the green grass. Suddenly, the snake quickly bit the boy's leg! The boy fell down in pain and cried, 'Why did you bite me? You promised!' The snake looked at him coldly and said, 'You knew I was a snake when you picked me up.'",
    dict: { "alone": "yalnız", "snowy": "karlı", "rattlesnake": "çıngıraklı yılan", "frozen": "donmuş", "begged": "yalvardı", "under": "altında", "warm": "sıcak", "jacket": "ceket", "die": "ölmek", "dangerous": "tehlikeli", "pick up": "yerden almak", "bite": "ısırmak", "promised": "söz verdi", "at no time": "hiçbir zaman", "saving": "kurtarıyor", "sorry": "üzgün", "reached": "ulaştı", "valley": "vadi", "grass": "çimen", "pain": "acı", "coldly": "soğuk bir şekilde" },
    questions: [ {q:"Was the snake freezing on the ground?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the boy trust the snake at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did the boy put the snake inside his jacket?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the snake promise to bite the boy?", a_en:"No", a_tr:"Hayır"}, {q:"Did the snake bite the boy in the warm valley?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the boy in pain?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the snake change its nature?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["05_ButterflyMonk.mp3"] = [{
    text: "The Butterfly and the Kind Monk. Two monks, an old teacher and a young student, were walking in a quiet garden. They saw a butterfly struggling to come out of its cocoon. The small butterfly was pushing hard, but the opening was too small. The young monk felt very sorry for the insect. He took his small knife and carefully cut the cocoon to help the butterfly. The butterfly came out easily, but its wings were small, weak, and folded. The young monk waited for it to fly, but it could only crawl on the ground. It flew at no point. The student was very upset and asked the old monk, 'Why can't it fly? I only wanted to help.' The old monk explained, 'By helping him, you actually hurt him. The struggle to get out of the tiny hole is nature’s way of strengthening the butterfly's muscles. It pushes fluid into the wings so they can fly. Because you interfered with the struggle, you made the butterfly lame forever.'",
    dict: { "monks": "keşişler", "struggling": "mücadele eden", "cocoon": "koza", "pushing": "itiyor/zorluyor", "opening": "açıklık", "sorry": "üzgün", "insect": "böcek", "carefully": "dikkatlice", "easily": "kolayca", "wings": "kanatlar", "weak": "zayıf", "folded": "katlanmış", "crawl": "emeklemek", "at no point": "hiçbir zaman", "upset": "üzgün", "explained": "açıkladı", "actually": "aslında", "hurt": "incitmek", "way": "yol/yöntem", "strengthening": "güçlendiren", "muscles": "kaslar", "fluid": "sıvı", "interfered": "müdahale etti", "lame": "topal/sakat", "forever": "sonsuza dek" },
    questions: [ {q:"Did the butterfly struggle to come out of its cocoon?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the young monk cut the cocoon?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the butterfly fly away immediately?", a_en:"No", a_tr:"Hayır"}, {q:"Were the butterfly's wings strong?", a_en:"No", a_tr:"Hayır"}, {q:"Does the struggle help the butterfly's muscles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the young monk's help hurt the butterfly?", a_en:"Yes", a_tr:"Evet"}, {q:"Can the butterfly fly now?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["06_CamelThistle.mp3"] = [{
    text: "The Camel and the Thistle. In the middle of the hot, dry desert, a hungry camel found a bush covered in sharp, bitter thorns. Most animals stayed away from the plant, but the camel began to eat it greedily. The sharp thorns quickly cut the camel’s tongue and the roof of its mouth. As it chewed, its own warm, salty blood began to flow and mix with the juices of the plant. To the camel, this made the thorns taste incredibly sweet and delicious. It realized at no point it was actually tasting its own blood. The more it ate, the more it bled, and the 'sweeter' the meal became. The camel was so focused on the sweet taste that it forgot the pain. It continued to eat until it finally collapsed and died from the loss of blood.",
    dict: { "middle": "orta", "desert": "çöl", "found": "buldu", "bush": "çalı", "covered": "kaplı", "bitter": "acı", "thorns": "dikenler", "stayed away": "uzak durdu", "plant": "bitki", "greedily": "açgözlülükle", "tongue": "dil", "roof of mouth": "damak", "chewed": "çiğnedi", "warm": "sıcak", "salty": "tuzlu", "blood": "kan", "flow": "akmak", "mix": "karışmak", "incredibly": "inanılmaz derecede", "sweet": "tatlı", "delicious": "lezzetli", "at no point": "hiçbir zaman", "bled": "kanadı", "focused": "odaklanmış", "collapsed": "yığıldı", "loss": "kayıp" },
    questions: [ {q:"Did the camel find a bush with thorns?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the camel eat the plant greedily?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the thorns cut the camel's tongue?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the sweet taste actually the camel's blood?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the camel realize it was eating its own blood?", a_en:"No", a_tr:"Hayır"}, {q:"Did the camel forget the pain?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the camel survive?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["07_CamelTent.mp3"] = [{
    text: "The Camel in the Tent. It was a freezing, windy night in the sandy desert. An Arab merchant was sleeping comfortably in his warm tent. His working camel was standing outside in the cold. The camel asked, 'Master, my nose is freezing. Can I put just my nose inside the tent?' The kind master said yes. A little later, the camel asked, 'Can I put my head and neck inside? It is very windy.' The master agreed again. Slowly, the clever camel put his front legs, and finally his whole heavy body into the tent. The tent was far too small for both of them. Because the camel was so big, he easily pushed the poor master out into the freezing night.",
    dict: { "freezing": "dondurucu", "windy": "rüzgarlı", "sandy": "kumlu", "merchant": "tüccar", "comfortably": "rahatça", "tent": "çadır", "outside": "dışarıda", "Master": "Efendi", "nose": "burun", "inside": "içeride", "later": "sonra", "neck": "boyun", "agreed": "kabul etti", "Slowly": "yavaşça", "front legs": "ön bacaklar", "whole": "bütün", "too small": "çok küçük", "both": "her ikisi", "easily": "kolayca", "pushed": "itti", "poor": "zavallı" },
    questions: [ {q:"Was it a warm night in the desert?", a_en:"No", a_tr:"Hayır"}, {q:"Was the merchant sleeping in a tent?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the camel ask to put just its nose inside first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the master say no to the camel?", a_en:"No", a_tr:"Hayır"}, {q:"Was the tent big enough for both?", a_en:"No", a_tr:"Hayır"}, {q:"Did the camel push the master out?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the master now outside in the cold?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_CatFox.mp3"] = [{
    text: "The Cat and the Fox. A quiet cat and a boastful fox were resting in the forest. The proud fox said, 'I am so smart! I know a hundred different tricks to escape from dangerous hunting dogs. I can run in circles, hide in bushes, and swim across rivers.' The humble cat listened carefully and said, 'I only know one simple trick. But it usually works for me.' Suddenly, they heard the loud, terrifying sound of hunting dogs running toward them. The cat immediately used her one simple trick. She quickly climbed straight up a very tall tree and hid safely in the high branches. The hungry dogs found no way to reach her. The fox, however, started thinking about his hundred different tricks. He tried running, then hiding, then swimming, but he was too confused and slow. The fast dogs easily caught the fox. From the high tree, the safe cat watched the boastful fox.",
    dict: { "quiet": "sessiz", "boastful": "böbürlenen", "resting": "dinleniyor", "smart": "akıllı", "hundred": "yüz", "tricks": "numaralar/hileler", "escape": "kaçmak", "hunting dogs": "av köpekleri", "circles": "daireler", "humble": "mütevazı", "simple": "basit", "usually": "genellikle", "terrifying": "korkunç", "immediately": "derhal", "climbed": "tırmandı", "straight up": "dosdoğru yukarı", "found no way": "hiçbir yol bulamadı", "reach": "ulaşmak", "thinking": "düşünüyor", "confused": "kafası karışmış", "caught": "yakaladı", "watched": "izledi" },
    questions: [ {q:"Did the fox know a hundred tricks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the cat know many tricks?", a_en:"No", a_tr:"Hayır"}, {q:"Did the cat climb a tall tree?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the dogs reach the cat?", a_en:"No", a_tr:"Hayır"}, {q:"Was the fox confused by his many plans?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dogs catch the fox?", a_en:"Yes", a_tr:"Evet"}, {q:"Is a simple plan often better?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_CrowPeacock.mp3"] = [{
    text: "The Crow and the Peacock Feathers. A normal black crow lived in a beautiful royal garden. He always watched the magnificent peacocks walking around the green grass. He felt very jealous of their bright, colorful feathers and their proud, elegant walk. One afternoon, the jealous crow found some beautiful blue and green peacock feathers lying on the ground. He quickly picked them up and stuck them tightly into his own black tail. He walked over to the peacocks and tried to act just like them. But the intelligent peacocks immediately saw his silly trick. They were very angry, pecked him with their sharp beaks, and chased him away. The sad, embarrassed crow went back to his old friends, the normal black crows. But the crows saw the leftover peacock feathers and completely refused to accept him back. 'If you are too ashamed to be a normal crow, you cannot live with us,' they said. The silly bird was left entirely alone.",
    dict: { "black crow": "kara karga", "magnificent": "muhteşem", "peacocks": "tavus kuşları", "jealous": "kıskanç", "colorful": "renkli", "feathers": "tüyler", "elegant": "zarif", "afternoon": "öğleden sonra", "lying": "uzanan/duran", "stuck": "yapıştırdı", "tightly": "sıkıca", "tail": "kuyruk", "intelligent": "zeki", "silly": "aptalca", "pecked": "gagalamak", "beaks": "gagalar", "chased": "kovaladı", "embarrassed": "utanmış", "leftover": "artık", "ashamed": "utanmış", "entirely": "tamamen" },
    questions: [ {q:"Was the crow jealous of the peacocks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the crow find colorful feathers on the ground?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the crow stick the feathers into his tail?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the peacocks happy to see him?", a_en:"No", a_tr:"Hayır"}, {q:"Did the peacocks peck the crow?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his old crow friends accept him back?", a_en:"No", a_tr:"Hayır"}, {q:"Is the crow now entirely alone?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_DeerAntlers.mp3"] = [{
    text: "The Deer and His Antlers. A thirsty brown deer went to a quiet, clear lake to drink some fresh water. While he was drinking, he looked at his own reflection in the water. He greatly admired his large, beautiful, branching antlers on his head. 'I look incredibly handsome and majestic,' he thought proudly. Then, he looked down at his thin, skinny legs. 'But my legs are so ugly and weak,' he complained sadly. Suddenly, a hungry lion jumped out of the tall grass! The frightened deer ran away as fast as he could. His thin, strong legs carried him very quickly, and he easily escaped the lion in the open field. But when the deer ran into the thick forest, his beautiful, large antlers got caught tightly in the tree branches. He could move no more! The lion finally caught him. The dying deer cried, 'The ugly legs I hated tried to save me, but the beautiful antlers I loved destroyed me.'",
    dict: { "thirsty": "susamış", "reflection": "yansıma", "admired": "hayran kaldı", "branching": "dallanan", "antlers": "boynuzlar", "majestic": "görkemli", "skinny": "zayıf/ince", "legs": "bacaklar", "ugly": "çirkin", "complained": "şikayet etti", "frightened": "korkmuş", "strong": "güçlü", "escaped": "kaçtı", "thick": "kalın/yoğun", "caught": "yakalandı", "branches": "dallar", "move no more": "artık hareket edememek", "hated": "nefret etti", "destroyed": "yok etti" },
    questions: [ {q:"Did the deer admire his antlers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the deer like his legs at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did a lion jump out of the grass?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his skinny legs help him run fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his antlers get caught in the tree branches?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the deer move after getting caught?", a_en:"No", a_tr:"Hayır"}, {q:"Did the beautiful antlers cause his death?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_DogReflection.mp3"] = [{
    text: "The Dog and His Reflection. A hungry street dog finally found a large, delicious piece of meat. He was very happy and decided to carry it home to eat in peace. On his way, he had to cross a narrow wooden bridge over a clear, deep river. He looked down into the water and saw his own reflection. However, he thought it was another dog carrying an even bigger piece of meat. The greedy dog wanted that second piece of meat too. He opened his mouth wide to bark and attack the 'other dog.' As soon as he opened his mouth, his own beautiful piece of meat fell straight into the fast river and disappeared. The silly dog was left with absolutely nothing for dinner.",
    dict: { "finally": "sonunda", "delicious": "lezzetli", "piece": "parça", "meat": "et", "carry": "taşımak", "peace": "huzur", "narrow": "dar", "wooden bridge": "ahşap köprü", "deep": "derin", "reflection": "yansıma", "However": "ancak", "another": "başka", "bigger": "daha büyük", "greedy": "açgözlü", "wide": "geniş", "bark": "havlamak", "attack": "saldırmak", "disappeared": "gözden kayboldu", "nothing": "hiçbir şey" },
    questions: [ {q:"Did the dog find a piece of meat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he cross a narrow bridge?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he see another real dog in the water?", a_en:"No", a_tr:"Hayır"}, {q:"Was the dog greedy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he open his mouth to bark?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the meat fall into the river?", a_en:"Yes", a_tr:"Evet"}, {q:"Does he have meat for dinner now?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["12_DogWolf.mp3"] = [{
    text: "The Dog and the Wolf. A hungry, skinny wolf was walking in the dark woods. He met a large, fat, and happy guard dog. The wolf said, 'You look so healthy and well-fed! I am always hungry and tired.' The dog smiled and said, 'Come live with my human master! I guard his house at night, and he gives me warm food, fresh water, and a soft bed.' The wolf was very excited to start this easy, comfortable life. But as they walked to the big house, the wolf noticed a large, red mark on the dog's neck. 'What is that painful mark?' the wolf asked carefully. 'Oh, that is nothing,' the dog answered. 'During the day, my master ties me to a thick, heavy chain so I run away at no time.' The wolf immediately stopped walking. 'You are tied up? You cannot run free?' The wolf turned around to go back to the cold forest. 'I prefer to be hungry and completely free,' he said, 'than to be fat and live as a slave.'",
    dict: { "skinny": "zayıf", "woods": "orman", "well-fed": "iyi beslenmiş", "human master": "insan efendi", "guard": "korumak", "fresh": "taze", "soft": "yumuşak", "comfortable": "rahat", "noticed": "fark etti", "mark": "iz", "neck": "boyun", "painful": "acılı", "ties": "bağlar", "thick": "kalın", "heavy chain": "ağır zincir", "at no time": "hiçbir zaman", "tied up": "bağlı", "run free": "özgürce koşmak", "prefer": "tercih etmek", "slave": "köle" },
    questions: [ {q:"Was the wolf very fat?", a_en:"No", a_tr:"Hayır"}, {q:"Did the dog have a human master?", a_en:"Yes", a_tr:"Evet"}, {q:"Was there a red mark on the dog's neck?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the master tie the dog to a chain?", a_en:"Yes", a_tr:"Evet"}, {q:"Can the dog run free during the day?", a_en:"No", a_tr:"Hayır"}, {q:"Did the wolf decide to stay at the house?", a_en:"No", a_tr:"Hayır"}, {q:"Does the wolf prefer freedom?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_DogManger.mp3"] = [{
    text: "The Dog in the Manger. A tired farm dog wanted to find a comfortable place to sleep. He jumped into a manger, which is a large wooden box where horses and cows eat their dry hay. Soon, a tired and very hungry horse came into the barn to eat his dinner. But the grumpy dog woke up, barked loudly, and showed his sharp teeth. He bit at the horse and refused to let him eat the food. The disappointed horse looked at the dog and said, 'You are a very selfish animal! You can eat the dry hay at no point yourself, but you will not let me eat it either. You are guarding something you need in no way.'",
    dict: { "farm dog": "çiftlik köpeği", "manger": "yemlik", "wooden box": "tahta kutu", "dry hay": "kuru saman", "barn": "ahır", "grumpy": "huysuz", "woke up": "uyandı", "sharp": "keskin", "refused": "reddetti", "disappointed": "hayal kırıklığına uğramış", "selfish": "bencil", "at no point": "hiçbir zaman/noktada", "guarding": "koruyor", "need": "ihtiyaç", "in no way": "hiçbir şekilde" },
    questions: [ {q:"Did the dog jump into a manger?", a_en:"Yes", a_tr:"Evet"}, {q:"Do horses eat dry hay?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the dog happy to see the horse?", a_en:"No", a_tr:"Hayır"}, {q:"Did the dog let the horse eat?", a_en:"No", a_tr:"Hayır"}, {q:"Can the dog eat the hay himself?", a_en:"No", a_tr:"Hayır"}, {q:"Is the dog being selfish?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the dog need the hay?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["14_DonkeyLapdog.mp3"] = [{
    text: "The Donkey and the Lapdog. A rich farmer had a big, hard-working donkey and a tiny, cute lapdog. The farmer loved the little dog very much. The happy dog sat on his lap, ate sweet treats from his hand, and slept inside the warm, safe house. The jealous donkey had to sleep in the cold barn and carry heavy wood all day long. The donkey thought, 'If I act exactly like the cute dog, the master will love me too!' One quiet evening, the huge donkey broke into the master's living room. He tried to jump playfully onto the farmer's lap, just like the tiny dog always did. The heavy donkey completely broke the chairs, smashed the wooden table, and hurt the terrified farmer. The angry farm workers quickly ran inside with heavy sticks. They hit the silly donkey and chased him back to the cold barn. The poor donkey was very confused; he only wanted to be loved like the little dog.",
    dict: { "donkey": "eşek", "lapdog": "süs köpeği", "lap": "diz/kucak", "sweet treats": "tatlı ödüller", "carry": "taşımak", "wood": "odun", "act": "davranmak", "living room": "oturma odası", "playfully": "oyunbaz bir şekilde", "smashed": "paramparça etti", "terrified": "dehşete düşmüş", "sticks": "sopalar", "chased": "kovaladı", "confused": "kafası karışmış" },
    questions: [ {q:"Did the farmer have a donkey and a tiny dog?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dog sleep in the cold barn?", a_en:"No", a_tr:"Hayır"}, {q:"Was the donkey jealous?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the donkey break the chairs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the farmer enjoy the donkey's jump?", a_en:"No", a_tr:"Hayır"}, {q:"Did the workers hit the donkey with sticks?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the donkey's place in the living room?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["15_DonkeySalt.mp3"] = [{
    text: "The Donkey and the Salt. A hard-working merchant owned a strong donkey. Every day, they carried heavy bags of expensive salt across a river. One morning, the donkey slipped and fell into the water. The salt quickly melted, and the bags became wonderfully light. The donkey was thrilled. The very next day, the donkey decided to fall into the river on purpose to make his work easy. The smart merchant watched this and understood the lazy trick. On the third day, the merchant filled the bags with soft, dry sponges instead of salt. The donkey happily fell into the water again. But this time, the sponges drank the heavy water, and the bags became incredibly heavy to carry.",
    dict: { "merchant": "tüccar", "bags": "torbalar", "expensive salt": "pahalı tuz", "river": "nehir", "slipped": "kaydı", "melted": "eridi", "light": "hafif", "thrilled": "heyecanlanmış", "on purpose": "bilerek", "lazy trick": "tembelce numara", "sponges": "süngerler", "instead of": "yerine", "heavy": "ağır", "incredibly": "inanılmaz derecede" },
    questions: [ {q:"Did the donkey carry bags of salt?", a_en:"Yes", a_tr:"Evet"}, {q:"Does salt melt in water?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the donkey fall on purpose the second time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the merchant understand the trick?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the merchant use sponges on the third day?", a_en:"Yes", a_tr:"Evet"}, {q:"Do dry sponges become light in water?", a_en:"No", a_tr:"Hayır"}, {q:"Was the donkey happy at the end?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["16_EagleArrow.mp3"] = [{
    text: "The Eagle and the Arrow. A beautiful, strong eagle was sitting high on a tall, rocky mountain. He was looking down at the green valley below. He felt very safe, proud, and powerful. However, a hunter was hiding quietly in the dark bushes on the ground. The hunter saw the magnificent bird, pulled his wooden bow, and shot a sharp arrow into the sky. The arrow flew perfectly straight and hit the great eagle right in the center of his heart. As the dying eagle was falling to the ground, he looked closely at the arrow in his chest. He saw that the feathers on the back of the arrow were actually eagle feathers. The eagle cried, 'This makes my death so much more painful! I am dying from a weapon that was made using my own feathers.'",
    dict: { "eagle": "kartal", "rocky": "kayalık", "valley": "vadi", "hunter": "avcı", "hiding": "saklanan", "bushes": "çalılar", "magnificent": "görkemli", "wooden bow": "tahta yay", "sharp arrow": "keskin ok", "heart": "kalp", "dying": "ölen", "closely": "yakından", "chest": "göğüs", "actually": "aslında", "feathers": "tüyler", "weapon": "silah" },
    questions: [ {q:"Was the eagle sitting on a mountain?", a_en:"Yes", a_tr:"Evet"}, {q:"Was a hunter hiding in the bushes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the hunter miss the eagle?", a_en:"No", a_tr:"Hayır"}, {q:"Did the arrow hit the eagle's heart?", a_en:"Yes", a_tr:"Evet"}, {q:"Were there eagle feathers on the arrow?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the eagle feel more pain because of his own feathers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the eagle survive?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["17_EagleBeetle.mp3"] = [{
    text: "The Eagle and the Beetle. A small hare was being chased by a massive eagle. The hare saw a tiny beetle and begged for help. The beetle turned to the eagle and said, 'Please, powerful bird, kill this poor animal at no point. He has asked for my protection.' The eagle laughed at the tiny insect and ate the hare right in front of him. The beetle was furious and decided to get revenge. He followed the eagle to her high nest. He waited for her to leave, and then he rolled her eggs out of the nest until they smashed on the rocks. The eagle moved her nest even higher, but the beetle found her again and destroyed the eggs. Finally, the eagle asked the King of the Gods for help. She laid her eggs in the King's lap for safety. The clever beetle flew over the King’s head and dropped a ball of dirt. When the King jumped up to brush the dirt away, the eggs fell and broke. The eagle was left with nothing.",
    dict: { "hare": "tavşan", "chased": "kovalanmış", "beetle": "böcek/kınkanatlı", "begged": "yalvardı", "at no point": "hiçbir zaman", "protection": "koruma", "furious": "öfkeli", "revenge": "intikam", "nest": "yuva", "eggs": "yumurtalar", "smashed": "parçalandı", "rocks": "kayalar", "King of the Gods": "Tanrıların Kralı", "lap": "kucak", "dirt": "kir/pislik", "nothing": "hiçbir şey" },
    questions: [ {q:"Did the beetle ask the eagle to save the hare?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the eagle listen to the beetle?", a_en:"No", a_tr:"Hayır"}, {q:"Did the beetle roll the eagle's eggs out of the nest?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the eagle move her nest higher?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the beetle find the nest again?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the beetle drop dirt on the King's head?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the eagle's eggs saved at the end?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["18_EagleChicken.mp3"] = [{
    text: "The Eagle Who Thought He Was a Chicken. High on a beautiful mountain, a mother eagle laid a large egg in her nest. One night, a strong earthquake shook the mountain. The eagle egg rolled down the rocks and landed safely in a chicken farm in the valley. When the egg hatched, a small eagle came out with the little chicks. The eagle grew up with his chicken siblings. He spent his days scratching the dirt for seeds. He never tried to fly because chickens fly at no time. One afternoon, he looked at the sky and saw a magnificent bird soaring above the clouds. 'I wish I could fly like that,' he cried. His chicken brother laughed, 'Be stupid at no point! That is a Great Eagle. You are just a chicken.' The eagle believed him. He died without ever knowing he was a king of the sky.",
    dict: { "egg": "yumurta", "earthquake": "deprem", "rolled down": "aşağı yuvarlandı", "landed": "indi", "valley": "vadi", "hatched": "yumurtadan çıktı", "chicks": "civcivler", "siblings": "kardeşler", "scratching": "tırmalıyor", "seeds": "tohumlar", "fly at no time": "hiçbir zaman uçmamak", "soaring": "süzülen", "above": "üstünde", "clouds": "bulutlar", "stupid": "aptal", "at no point": "hiçbir zaman", "knowing": "bilerek" },
    questions: [ {q:"Did the eagle egg land on a chicken farm?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the eagle grow up with chickens?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he try to fly every day?", a_en:"No", a_tr:"Hayır"}, {q:"Did chickens fly in this story?", a_en:"No", a_tr:"Hayır"}, {q:"Did the eagle see a magnificent bird in the sky?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the eagle believe he was a chicken?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he ever learn how to fly?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["19_ElephantRope.mp3"] = [{
    text: "The Elephant and the Rope. A curious traveler was visiting a large circus camp. He saw a huge adult elephant standing quietly. The elephant was tied to a wooden pole with only a very thin, small rope. The traveler was very surprised. He asked the trainer, 'Why does this giant animal find no way to break that weak rope and run away?' The trainer explained, 'When he was a baby, we used this exact same rope to tie him. Back then, it was strong enough. He tried to break it many times, but he failed. Now he is big and powerful, but he still believes the rope can hold him. Because he thinks he can do it at no point, he never even tries anymore.' The elephant was trapped not by the rope, but by his own mind.",
    dict: { "curious": "meraklı", "circus camp": "sirk kampı", "adult": "yetişkin", "tied": "bağlanmış", "wooden pole": "tahta direk", "thin": "ince", "rope": "ip", "trainer": "eğitici", "find no way": "hiçbir yol bulamamak", "break": "kırmak", "enough": "yeterli", "failed": "başarısız oldu", "hold": "tutmak", "at no point": "hiçbir zaman", "trapped": "kapana kısılmış", "mind": "akıl/zihin" },
    questions: [ {q:"Was the elephant tied with a very thick chain?", a_en:"No", a_tr:"Hayır"}, {q:"Was the elephant tied to a wooden pole?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the elephant try to break the rope as a baby?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the elephant fail to break the rope as a baby?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the elephant powerful enough to break the rope now?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the elephant try to break the rope now?", a_en:"No", a_tr:"Hayır"}, {q:"Was the elephant trapped by his own mind?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_FalconKing.mp3"] = [{
    text: "The Falcon and the King. A powerful King had a favorite hunting falcon. One hot summer day, the King went hunting in the dry forest. He became very thirsty and found a small stream of water dripping from a rock. He filled his golden cup slowly. Just as he was about to drink, the falcon flew down and knocked the cup out of his hand. The King filled the cup again, but again, the falcon attacked it. The third time, the King was so angry that he killed the falcon with his sword. As the bird died, the King looked up at the top of the rock. He saw a huge, dead poisonous snake lying in the water source. The water was toxic! The falcon was trying to save his master’s life. The King cried in deep sadness, but it was too late.",
    dict: { "powerful": "güçlü", "hunting falcon": "avcı doğanı", "thirsty": "susamış", "stream": "dere", "dripping": "damlayan", "golden cup": "altın kupa", "knocked": "vurdu/devirdi", "attacked": "saldırdı", "sword": "kılıç", "poisonous snake": "zehirli yılan", "water source": "su kaynağı", "toxic": "zehirli", "save": "kurtarmak", "deep sadness": "derin üzüntü" },
    questions: [ {q:"Did the King have a favorite falcon?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the King very thirsty?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the falcon knock the cup out of his hand?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the King kill the falcon in anger?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the water safe to drink?", a_en:"No", a_tr:"Hayır"}, {q:"Was there a dead poisonous snake in the water?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the falcon try to save the King's life?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_FoxStork.mp3"] = [{
    text: "The Fox and the Stork. A clever fox invited a tall stork to dinner. The fox prepared delicious soup, but he served it on a very flat, shallow plate. The fox quickly licked up the soup, but the stork could eat nothing because her beak was too long. The cruel fox just laughed. The next day, the stork invited the fox for dinner. She prepared wonderful meat, but she served it inside a tall, thin glass jar. The stork ate easily by putting her long beak inside, but the fox found no way to fit his wide head into the jar. The fox had to go home completely hungry and embarrassed.",
    dict: { "invited": "davet etti", "prepared": "hazırladı", "served": "servis etti", "flat": "düz", "shallow": "sığ", "plate": "tabak", "licked up": "yaladı", "beak": "gaga", "cruel": "zalim", "meat": "et", "glass jar": "cam kavanoz", "fit": "sığmak", "wide": "geniş", "head": "kafa", "embarrassed": "utanmış" },
    questions: [ {q:"Did the fox serve soup on a flat plate?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the stork eat from the flat plate?", a_en:"No", a_tr:"Hayır"}, {q:"Did the fox laugh at the stork?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the stork invite the fox the next day?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the stork serve meat in a tall jar?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the fox fit his head into the jar?", a_en:"No", a_tr:"Hayır"}, {q:"Did the fox go home hungry?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["22_FoxTraitorRooster.mp3"] = [{
    text: "The Fox and the Traitor Rooster. A smart farmer built a strong chicken coop. A hungry fox wanted to get inside, but the door was locked. He found a tiny hole and started dropping extra corn through it for one specific rooster every night. Because of this food, the rooster grew big and became the boss of the coop. One night, the fox whispered, 'I made you the boss. Now, do me a favor. Open the door from the inside.' The rooster felt special and opened the heavy door. The fox rushed in and ate the chickens. Finally, he grabbed the boss rooster. The rooster cried, 'Wait! We are friends!' The fox laughed, 'Someone who betrays his family for a little corn is a friend to nobody.'",
    dict: { "chicken coop": "tavuk kümesi", "locked": "kilitli", "hole": "delik", "dropping": "bırakıyor/atıyor", "corn": "mısır", "specific": "belirli", "rooster": "horoz", "whispered": "fısıldadı", "favor": "iyilik", "special": "özel", "heavy": "ağır", "rushed": "daldı/koştu", "grabbed": "yakaladı", "betrays": "ihanet eder", "nobody": "hiç kimse" },
    questions: [ {q:"Was the chicken coop door locked?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fox give corn to a specific rooster?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rooster become the boss?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rooster open the door for the fox?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fox eat the chickens?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the fox a true friend to the rooster?", a_en:"No", a_tr:"Hayır"}, {q:"Is a traitor respected by an enemy?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["23_FrogsWantedKing.mp3"] = [{
    text: "The Frogs Who Wanted a King. A large family of frogs lived peacefully in a quiet lake. However, they soon thought, 'We need a strong King to rule our society.' They prayed to the sky gods for a King. The gods laughed and threw a heavy wooden log into the lake. It made a loud splash! The frogs were terrified at first, but the log just floated and did nothing. The frogs got bored and complained, 'This King is too lazy! We want a strong, active King!' The gods became angry at their foolishness and sent a large, hungry water snake. The snake immediately became their new King and started eating the frogs one by one.",
    dict: { "peacefully": "huzur içinde", "lake": "göl", "rule": "yönetmek", "society": "toplum", "prayed": "dua ettiler", "wooden log": "odun kütüğü", "splash": "su sesi/sıçratma", "floated": "yüzdü", "bored": "sıkılmış", "active": "aktif/hareketli", "foolishness": "aptallık", "water snake": "su yılanı", "one by one": "tek tek" },
    questions: [ {q:"Did the frogs live peacefully at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they ask the gods for a King?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the first King a wooden log?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the log King eat the frogs?", a_en:"No", a_tr:"Hayır"}, {q:"Did the frogs want a more active King?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the second King a hungry snake?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the snake eat the frogs?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["24_GooseGoldenEggs.mp3"] = [{
    text: "The Goose and the Golden Eggs. A poor farmer bought a white goose. The next morning, he found a shiny yellow egg in the nest. It was made of pure gold! Every morning, the magical goose laid exactly one golden egg. The farmer quickly became very rich. However, he also became very impatient and greedy. He thought, 'This goose must have a huge pile of gold inside its stomach! If I cut it open, I can have all the gold right now.' He took a knife and killed the poor goose. But when he opened it, he found nothing. It was just a normal bird inside. The greedy farmer lost his magical bird forever.",
    dict: { "bought": "satın aldı", "shiny": "parlak", "nest": "yuva", "pure": "saf", "gold": "altın", "magical": "sihirli", "laid": "yumurtladı", "rich": "zengin", "impatient": "sabırsız", "greedy": "açgözlü", "huge pile": "büyük yığın", "stomach": "mide", "knife": "bıçak", "nothing": "hiçbir şey" },
    questions: [ {q:"Did the goose lay golden eggs every morning?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the farmer become rich?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the farmer patient?", a_en:"No", a_tr:"Hayır"}, {q:"Did the farmer kill the goose?", a_en:"Yes", a_tr:"Evet"}, {q:"Was there a pile of gold inside the goose?", a_en:"No", a_tr:"Hayır"}, {q:"Was it a normal bird inside?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the farmer lose his magical bird forever?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["25_HeronFish.mp3"] = [{
    text: "The Heron and the Fish. A tall, elegant heron stood by a quiet pond. He saw many small fish swimming near his feet. 'No,' the heron thought proudly. 'I will eat no such tiny, unimportant fish. I will wait for a large fish fit for a king.' Later, a medium-sized perch swam past. The heron looked at it with his nose in the air. 'Still good enough at no point,' he said. The sun began to set, and the larger fish moved into the deep water where the heron found no way to reach them. The small fish also swam away to hide. The proud heron stayed in the water for a long time, but he found nothing else to eat. Finally, the hungry bird had to eat a small, slimy snail from the mud.",
    dict: { "heron": "balıkçıl kuşu", "pond": "gölet", "proudly": "gururla", "tiny": "küçücük", "unimportant": "önemsiz", "fit": "uygun", "medium-sized": "orta boy", "perch": "levrek", "set": "batmak (güneş)", "deep": "derin", "slimy": "vıcık vıcık/sümüklü", "snail": "salyangoz", "mud": "çamur" },
    questions: [ {q:"Did the heron see small fish at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to eat the small fish?", a_en:"No", a_tr:"Hayır"}, {q:"Did he wait for a larger fish?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he catch a large fish?", a_en:"No", a_tr:"Hayır"}, {q:"Did the small fish swim away?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the heron find a large fish in the end?", a_en:"No", a_tr:"Hayır"}, {q:"Did he have to eat a snail?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["26_HorseLoadedDonkey.mp3"] = [{
    text: "The Horse and the Loaded Donkey. A proud horse and a tired donkey were traveling with their master. The donkey was carrying a very heavy load of bags, but the horse was carrying nothing but a beautiful saddle. After walking for hours, the donkey felt very weak. He looked at the horse and begged, 'Please, friend, take just a small part of my load. If you give no help to me, I will certainly die.' The horse held his head high and replied, 'Why should I help you? I am a noble animal, and I carry no heavy bags.' The donkey said nothing more, but a few miles later, he collapsed and died from exhaustion. The master was very upset. He took all the heavy bags from the dead donkey and put them on the horse's back. Then, he also took the donkey’s heavy skin and placed it on top of the bags. The horse cried, 'I was so selfish! By refusing to help, I now have to carry everything alone.'",
    dict: { "loaded": "yüklü", "master": "efendi/sahip", "heavy load": "ağır yük", "saddle": "eyer", "weak": "zayıf/güçsüz", "begged": "yalvardı", "certainly": "kesinlikle", "noble": "asil", "collapsed": "yığıldı", "exhaustion": "bitkinlik", "upset": "üzgün", "skin": "deri", "selfish": "bencil" },
    questions: [ {q:"Was the donkey carrying a heavy load?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the horse carrying heavy bags at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did the donkey ask for help?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the horse help the donkey?", a_en:"No", a_tr:"Hayır"}, {q:"Did the donkey die from exhaustion?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the master put the bags on the horse's back?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the horse carry the donkey's skin too?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["27_HorseStagRider.mp3"] = [{
    text: "The Horse, the Stag, and the Rider. A wild horse and a large stag lived in the same meadow. They constantly fought over the sweetest grass. The stag was stronger, so he finally chased the horse away. The horse wanted revenge. He went to a hunter and asked for help. The man said, 'I will help you, but you must let me put a metal bit in your mouth and a saddle on your back.' The angry horse agreed. The man climbed on the horse, and together they easily chased the stag away. The horse was very happy. He said, 'Thank you! Now take this saddle off.' The man laughed loudly. 'No, my friend. I like riding you.' The horse became a slave forever.",
    dict: { "stag": "geyik (erkek)", "rider": "binici", "meadow": "çayır", "constantly": "sürekli", "grass": "ot/çimen", "chased away": "kovdu", "revenge": "intikam", "hunter": "avcı", "bit": "gem (at için)", "slave": "köle" },
    questions: [ {q:"Did the horse and stag fight over grass?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the stag stronger?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the horse ask a hunter for help?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the horse agree to wear a saddle?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they chase the stag away?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the man take the saddle off?", a_en:"No", a_tr:"Hayır"}, {q:"Did the horse lose its freedom?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["28_LazySwallow.mp3"] = [{
    text: "The Lazy Swallow and the Winter. Summer was ending, and the air was becoming cold. All the birds in the forest started to prepare for their long trip to the warm south. They practiced flying every day to build their strength. However, one young swallow was very lazy. He loved eating delicious flies and napping in the afternoon sun. When the older birds told him it was time to leave, the swallow laughed. 'The sun is still warm today,' he said. 'I want to play for one more week. I am fast, so I will catch up with you later.' He ignored his friends and continued to sleep. One morning, the swallow woke up and realized the forest was completely quiet. All the other birds had flown away. Suddenly, a terrible snowstorm arrived. The swallow tried to fly south, but he was prepared at no level. The freezing wind made his wings stiff and heavy with ice. He was too weak to fight the cold air. Finally, he fell from the sky and landed in a deep, white snowfield, shivering and alone.",
    dict: { "swallow": "kırlangıç", "south": "güney", "strength": "güç", "napping": "şekerleme yapma", "catch up": "yetişmek", "ignored": "görmezden geldi", "snowstorm": "kar fırtınası", "stiff": "sert/kaskatı", "shivering": "titreyen" },
    questions: [ {q:"Did the birds prepare to fly south?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the young swallow hardworking?", a_en:"No", a_tr:"Hayır"}, {q:"Did the swallow want to play for another week?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the swallow fly south with his friends?", a_en:"No", a_tr:"Hayır"}, {q:"Did a snowstorm arrive?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the swallow's wings covered in ice?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the swallow prepared for winter?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["29_LionCleverRabbit.mp3"] = [{
    text: "The Lion and the Clever Rabbit. A hungry lion lived in a forest and ate many animals every day. The animals said, 'King, if you stop hunting us, we will send one animal to your cave every day for dinner.' The lion agreed. One day, it was the rabbit's turn. The rabbit arrived late. The lion was furious. 'Why are you late?' he roared. The rabbit whispered, 'Another lion stopped me. He said he is the true King.' The lion screamed, 'Take me to him!' The rabbit led the lion to a deep well. 'He is hiding inside', the rabbit said. The lion looked down and saw his own reflection. He thought it was the enemy. He roared, and the reflection 'roared' back. The angry lion jumped into the well to attack and drowned.",
    dict: { "hunting": "avlanma", "cave": "mağara", "turn": "sıra", "late": "geç", "furious": "öfkeli", "roared": "kükredi", "well": "kuyu", "reflection": "yansıma", "drowned": "boğuldu" },
    questions: [ {q:"Did the lion eat many animals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the animals send one animal every day?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the rabbit early?", a_en:"No", a_tr:"Hayır"}, {q:"Did the rabbit lie about another lion?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lion see his own reflection in the well?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lion jump into the well?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lion survive?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["30_LionMouse.mp3"] = [{
    text: "The Lion and the Mouse. A huge, sleeping lion caught a tiny mouse under his paw. The terrified mouse cried, 'Please eat me at no point! If you let me go, I promise I will help you one day.' The lion laughed. 'How can a tiny mouse help a powerful lion?' But the lion let the mouse go free. A few weeks later, hunters trapped the lion in a strong rope net. The lion roared in fear. The little mouse heard the roar, ran over, and used his sharp teeth to cut the thick ropes, freeing the big lion.",
    dict: { "tiny": "küçücük", "paw": "pençe", "terrified": "dehşete düşmüş", "let go": "serbest bırakmak", "hunters": "avcılar", "trapped": "kapana kıstı", "rope net": "ip ağ", "sharp teeth": "keskin dişler" },
    questions: [ {q:"Did the lion catch a mouse?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the mouse promise to help the lion?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lion believe the mouse at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did the lion let the mouse go free?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the lion trapped in a net later?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the mouse cut the ropes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the mouse save the lion?", a_en:"Yes", a_tr:"Evet"} ]
}];lessonData["31_LionPainting.mp3"] = [{
    text: "The Lion and the Painting. A proud lion and a human traveler were arguing about who was stronger. The man said humans were the strongest, but the lion disagreed. Suddenly, they saw a stone statue showing a strong human hunter killing a massive lion. The man pointed at the statue. 'Look! This proves that humans are much stronger than any lion.' The lion laughed. 'That is true at no point,' the lion replied. 'A human artist made this statue to make himself look good. If a lion could build statues, you would see the lion standing on top of the human.' The man became very quiet. He realized the truth depends on the artist.",
    dict: { "traveler": "gezgin", "arguing": "tartışıyor", "stronger": "daha güçlü", "disagreed": "aynı fikirde değildi", "stone statue": "taş heykel", "massive": "devasa", "proves": "kanıtlar", "at no point": "hiçbir zaman", "depends": "bağlıdır" },
    questions: [ {q:"Were the man and lion arguing?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the man think humans were stronger?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the statue show a lion killing a man?", a_en:"No", a_tr:"Hayır"}, {q:"Did a human artist make the statue?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lion agree with the statue?", a_en:"No", a_tr:"Hayır"}, {q:"Does the story depend on who tells it?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the man quiet at the end?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["32_LionDonkeyFox.mp3"] = [{
    text: "The Lion, the Donkey, and the Fox. A lion, a donkey, and a fox went hunting together. They caught a huge amount of food. The lion ordered the donkey to divide the food. The honest donkey divided the food into three equal parts. The lion became furious and killed the donkey. Then, the lion told the fox to divide the food. The clever fox pushed almost all of the food to the lion and kept only a tiny piece for himself. The lion smiled and asked, 'Who taught you to divide so well?' The fox answered, 'The dead donkey.'",
    dict: { "amount": "miktar", "ordered": "emretti", "divide": "bölmek/paylaştırmak", "honest": "dürüst", "equal": "eşit", "pushed": "itti", "almost": "neredeyse", "tiny": "küçücük" },
    questions: [ {q:"Did they go hunting together?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the donkey divide the food equally?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the lion happy with the donkey?", a_en:"No", a_tr:"Hayır"}, {q:"Did the lion kill the donkey?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fox give most of the food to the lion?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the lion happy with the fox?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fox learn from the donkey's mistake?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["33_LionsDividedHerd.mp3"] = [{
    text: "The Lions and the Divided Herd. A herd of buffalos lived together in a valley. A group of lions watched them but were afraid to attack because the buffalos were too strong together. The leader of the lions said, 'We only want that Yellow Cow. If you give her to us, we promise to attack the rest of you at no time.' The older buffalos warned the others, but the younger ones sent the Yellow Cow to the lions. The lions ate her and stayed quiet. Soon, the lions asked for another buffalo, and then another. Each time, the herd became smaller. Finally, the lions attacked everyone. As the last buffalo died, he cried, 'We were defeated the day we gave away the Yellow Cow.'",
    dict: { "herd": "sürü", "buffalos": "mandalar", "valley": "vadi", "afraid": "korkmuş", "warned": "uyardı", "smaller": "daha küçük", "defeated": "yenilmiş", "gave away": "feda ettik/verdik" },
    questions: [ {q:"Were the buffalos strong together?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the lions afraid at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lions ask for the Yellow Cow?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the buffalos send the Yellow Cow to the lions?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lions stop attacking forever?", a_en:"No", a_tr:"Hayır"}, {q:"Did the herd become smaller over time?", a_en:"Yes", a_tr:"Evet"}, {q:"Is unity important for protection?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["34_LittleBirdCow.mp3"] = [{
    text: "The Little Bird and the Cow. It was a freezing winter day. A small bird was flying, but the air was too cold. Its wings froze, and it fell into a snowy field, slowly dying of cold. Just then, a large brown cow walked past. The cow dropped a big, warm pile of manure right on top of the little bird. At first, the bird was angry. But then, it felt the wonderful heat. The warm manure melted the ice and saved its life! The bird felt so happy that it started to sing a loud song. However, a hungry farm cat heard the happy singing. The cat quickly found the bird inside the manure, pulled it out, and ate it.",
    dict: { "froze": "dondu", "field": "alan/tarla", "brown": "kahverengi", "pile": "yığın", "manure": "gübre", "melted": "eritti", "singing": "şarkı söyleme", "pulled out": "çıkardı" },
    questions: [ {q:"Did the bird's wings freeze?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bird fall into the snow?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the cow drop warm manure on the bird?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the manure save the bird's life?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bird stay quiet?", a_en:"No", a_tr:"Hayır"}, {q:"Did a cat hear the bird singing?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the cat eat the bird?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["35_MiceWantedBell.mp3"] = [{
    text: "The Mice Who Wanted a Bell. A group of mice lived in a big house but were terrified of the house cat. They held a meeting to fix the problem. A young mouse said, 'I have a brilliant idea! We will tie a bell around the cat's neck. When the cat walks, we will hear the bell and run away!' All the mice cheered. They thought it was a perfect plan. Then, an old, wise mouse asked, 'Yes, it is a fantastic plan. But tell me, who exactly is going to put the bell on the cat?' Everyone suddenly became very quiet.",
    dict: { "mice": "fareler", "terrified": "dehşete düşmüş", "bell": "zil", "around": "etrafına", "cheered": "tezahürat yaptılar", "exactly": "tam olarak", "quiet": "sessiz" },
    questions: [ {q:"Were the mice afraid of the cat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the young mouse have an idea?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the plan to tie a bell on the cat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did all the mice cheer for the plan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did an old mouse ask a difficult question?", a_en:"Yes", a_tr:"Evet"}, {q:"Did any mouse volunteer to put the bell on?", a_en:"No", a_tr:"Hayır"}, {q:"Is a clever plan easy to execute?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["36_MonkeyCrocodile.mp3"] = [{
    text: "The Monkey and the Crocodile. A clever monkey lived in an apple tree next to a river. He often threw apples to a crocodile, and they became friends. However, the crocodile's wife was greedy. She told her husband, 'This monkey's heart must be delicious! I want to eat it.' The crocodile invited the monkey to his home and carried him on his back. In the middle of the river, the crocodile confessed, 'My wife wants to eat your heart.' The monkey was terrified but stayed calm. He said, 'Oh no! I left my heart back in the tree for safety. Take me back to get it!' The crocodile swam back, and the monkey escaped.",
    dict: { "apple tree": "elma ağacı", "wife": "eş/karı", "heart": "kalp", "delicious": "lezzetli", "carried": "taşıdı", "confessed": "itiraf etti", "safety": "güvenlik", "escaped": "kaçı" },
    questions: [ {q:"Were the monkey and crocodile friends at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the crocodile's wife want to eat the monkey?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the crocodile carry the monkey on his back?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the crocodile tell the truth in the river?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the monkey stay calm?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the monkey's heart really in the tree?", a_en:"No", a_tr:"Hayır"}, {q:"Did the monkey escape?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["37_MouseFrogHawk.mp3"] = [{
    text: "The Mouse, the Frog, and the Hawk. A field mouse and a frog were friends. One day, the playful frog tied the mouse's foot to his own leg with a piece of grass. They walked together looking for food. Suddenly, the frog jumped into a deep pond. The frog loved the water, but the mouse found no way to swim and drowned. The dead mouse's body floated to the top, still tied to the frog. A hungry hawk saw the dead mouse, flew down, and grabbed it. Because the frog was tied to the mouse, the hawk easily pulled the frog out of the water too, and ate them both.",
    dict: { "field mouse": "tarla faresi", "tied": "bağladı", "foot": "ayak", "piece": "parça", "grass": "ot", "pond": "gölet", "drowned": "boğuldu", "floated": "yüzdü (su üstünde)", "hawk": "şahin/atmaca", "both": "her ikisi" },
    questions: [ {q:"Did the frog tie the mouse's foot?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the frog jump into a pond?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the mouse swim?", a_en:"No", a_tr:"Hayır"}, {q:"Did the mouse drown?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a hawk saw the dead mouse?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the hawk grab only the mouse?", a_en:"No", a_tr:"Hayır"}, {q:"Did the hawk eat both of them?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["38_NightingaleHawk.mp3"] = [{
    text: "The Nightingale and the Hawk. A hungry hawk caught a tiny nightingale. The nightingale begged, 'Please let me go. I am so small. You should wait for a bigger bird.' The hawk shook his head. 'I would be very foolish to listen to you,' the hawk said. 'I have you in my claws right now. If I let you go, I might find nothing else. A small bird in my claw is much better than a large bird that is still flying in the sky.' The hawk gave no ear to the nightingale’s words and ate his meal. He knew that the future is never certain, but the present is real.",
    dict: { "nightingale": "bülbül", "caught": "yakaladı", "claws": "pençeler", "foolish": "aptalca", "gave no ear": "kulak asmadı", "words": "kelimeler", "certain": "kesin", "present": "şimdiki zaman/şu an" },
    questions: [ {q:"Did the hawk catch a nightingale?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the nightingale ask to be set free?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the hawk let the bird go?", a_en:"No", a_tr:"Hayır"}, {q:"Did the hawk want to wait for a bigger bird?", a_en:"No", a_tr:"Hayır"}, {q:"Is a bird in the claw better than one in the sky?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the hawk eat the nightingale?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the future always certain?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["39_OakTreeReed.mp3"] = [{
    text: "The Oak Tree and the Reed. A strong oak tree stood next to a fast river. Near its roots, some thin reeds were growing. The arrogant oak tree said, 'I am so powerful. I bend for the wind at no point. You poor reeds are weak; you bow down to every small breeze.' That night, a violent storm arrived. The oak tree stubbornly fought the wind, but its trunk broke and it crashed down. The soft reeds simply bent flat to the ground with the wind. When the storm passed, the flexible reeds stood back up again safely.",
    dict: { "oak tree": "meşe ağacı", "reed": "kamış", "roots": "kökler", "at no point": "hiçbir zaman", "weak": "zayıf", "bow down": "eğilmek", "breeze": "meltem/esinti", "violent storm": "şiddetli fırtına", "stubbornly": "inatla", "trunk": "gövde", "crashed": "devrildi/çöktü", "flexible": "esnek" },
    questions: [ {q:"Was the oak tree arrogant?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the oak tree bend for the wind at first?", a_en:"No", a_tr:"Hayır"}, {q:"Were the reeds weak but flexible?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a violent storm arrive?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the oak tree's trunk break?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the reeds survive the storm?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it sometimes better to be flexible?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["40_OldDogHole.mp3"] = [{
    text: "The Old Dog and the Hole. An old farm dog fell into a deep, dry hole. The farmer thought the dog was too old to save, so he decided to bury the dog there. He began to throw dirt into the hole. When the first shovel of dirt hit the dog's back, it was terrified. But then, the dog had a smart idea. Every time dirt landed on him, he would shake it off and step on top of it. Slowly, the pile of dirt grew higher. Finally, the dog reached the top of the hole and jumped out. The farmer was amazed that the dirt he used to bury the dog was actually what saved him.",
    dict: { "dry hole": "kuru delik/çukur", "bury": "gömmek", "throw": "atmak", "shovel": "kürek", "shake it off": "silkelemek", "step on top": "üzerine basmak", "amazed": "hayret etmiş" },
    questions: [ {q:"Did the old dog fall into a hole?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the farmer try to save the dog at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did the farmer throw dirt on the dog?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dog shake the dirt off?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dog step on top of the dirt?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dog reach the top of the hole?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dirt save the dog's life?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["41_OldLionFootprints.mp3"] = [{
    text: "The Old Lion and the Footprints. An old, weak lion could hunt no longer, so he made a plan. He went into his dark cave and pretended to be very sick. Many animals felt sorry for the king and went inside to visit him. As soon as they entered, the lion ate them. A smart fox stayed outside safely. He called out, 'How are you feeling today, King?' The lion answered, 'I am very sick. Please, come inside.' The fox looked at the ground and smiled. 'No, thank you', the fox said. 'I can see many footprints going into your cave, but I see footprints coming out at no point.'",
    dict: { "weak": "zayıf/güçsüz", "hunt no longer": "artık avlanamamak", "cave": "mağara", "pretended": "numara yaptı", "sick": "hasta", "inside": "içeri/içeride", "visit": "ziyaret etmek", "entered": "girdiler", "ate": "yedi", "safely": "güvenli bir şekilde", "called out": "seslendi", "ground": "yer/zemin", "footprints": "ayak izleri", "at no point": "hiçbir zaman/noktada" },
    questions: [ {q:"Could the old lion hunt any longer?", a_en:"No", a_tr:"Hayır"}, {q:"Did the lion pretend to be sick?", a_en:"Yes", a_tr:"Evet"}, {q:"Did many animals visit the lion in his cave?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lion eat the animals that entered?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the smart fox go inside the cave?", a_en:"No", a_tr:"Hayır"}, {q:"Did the fox see any footprints coming out of the cave?", a_en:"No", a_tr:"Hayır"}, {q:"Did the fox see footprints coming out at no point?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["42_OldManScorpion.mp3"] = [{
    text: "The Old Man and the Scorpion. A wise old man saw a scorpion struggling in a river. He reached out to save it, but the scorpion stung his hand. A minute later, he tried again, and the scorpion stung him a second time. A traveler shouted, 'Why do you keep trying to save that creature? It is only going to sting you!' The old man replied, 'It is the scorpion's nature to sting. But it is my nature to be kind. Why should I let his bad nature change my good nature?' He used a long leaf to pull the scorpion out safely.",
    dict: { "wise": "bilge", "scorpion": "akrep", "struggling": "mücadele eden", "reached out": "uzandı", "save": "kurtarmak", "stung": "soktu", "later": "sonra", "tried": "denedi", "second time": "ikinci kez", "shouted": "bağırdı", "creature": "yaratık", "replied": "cevap verdi", "nature": "doğa/fıtrat", "leaf": "yaprak" },
    questions: [ {q:"Did the wise old man try to save the scorpion?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the scorpion sting the man's hand?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the man give up after the first sting?", a_en:"No", a_tr:"Hayır"}, {q:"Was it the scorpion's nature to sting?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the man let the scorpion change his good nature?", a_en:"No", a_tr:"Hayır"}, {q:"Did the man use a leaf to pull the scorpion out?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the scorpion saved at the end?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["43_PeacockCrane.mp3"] = [{
    text: "The Peacock and the Crane. A peacock was showing his colorful feathers to a gray crane. 'Look at me!' the peacock boasted. 'I am covered in gold and purple. You are so ugly and dusty.' The crane spread his wings and flew into the clouds. He looked down and shouted, 'It is true that your feathers are beautiful. But you stay on the ground like a chicken. I may be gray, but my wings carry me to the stars. I prefer my freedom to your beauty.' The peacock stayed on the ground, feeling very small.",
    dict: { "peacock": "tavus kuşu", "crane": "turna kuşu", "boasted": "böbürlendi", "covered": "kaplı", "purple": "mor", "ugly": "çirkin", "dusty": "tozlu", "spread": "yaydı/açtı", "clouds": "bulutlar", "freedom": "özgürlük", "beauty": "güzellik", "feeling small": "küçük hissetmek" },
    questions: [ {q:"Was the peacock boasting about his feathers?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the crane covered in purple and gold?", a_en:"No", a_tr:"Hayır"}, {q:"Could the peacock fly high into the clouds?", a_en:"No", a_tr:"Hayır"}, {q:"Did the crane fly into the sky?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the crane prefer freedom to beauty?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the peacock stay on the ground?", a_en:"Yes", a_tr:"Evet"}, {q:"Is physical beauty the most important thing?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["44_WomanMongoose.mp3"] = [{
    text: "The Peasant Woman and the Mongoose. A peasant woman found a small, orphaned mongoose in the forest. Her neighbors warned her, 'Be careful! That animal naturally preys on birds. One day, he will eat all your chickens.' But the woman was kind and gave no ear to them. She fed the mongoose and kept him near her chicken coop. The mongoose grew fast and became very loyal. One afternoon, the woman went to the market. When she returned, she saw the mongoose standing by the gate. His mouth was covered in fresh, red blood. The woman panicked. 'My neighbors were right!' she screamed. 'You have killed my chickens!' In a fit of rage, she grabbed a heavy shovel and killed the mongoose with one blow. Then, she ran to the coop. To her shock, all her chickens were alive and safe. In the corner of the coop, she saw a massive, poisonous snake torn to pieces. She realized the mongoose had fought the snake to protect her farm. She sat on the ground and cried for her brave friend.",
    dict: { "peasant": "köylü", "mongoose": "mongoos/firavun faresi", "orphaned": "yetim kalmış", "warned": "uyardı", "gave no ear": "kulak asmadı", "fed": "besledi", "chicken coop": "tavuk kümesi", "loyal": "sadık", "returned": "döndü", "gate": "kapı/geçit", "blood": "kan", "fit of rage": "öfke krizi", "shovel": "kürek", "blow": "darbe", "massive": "devasa", "poisonous": "zehirli", "torn to pieces": "parçalanmış", "realized": "fark etti", "protect": "korumak" },
    questions: [ {q:"Did the woman find an orphaned mongoose?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she give any ear to her neighbors' warnings?", a_en:"No", a_tr:"Hayır"}, {q:"Did the mongoose become loyal?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the mongoose's mouth covered in blood?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the woman kill the mongoose in a fit of rage?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the mongoose kill the chickens?", a_en:"No", a_tr:"Hayır"}, {q:"Did the mongoose kill a massive poisonous snake?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["45_PeasantSnake.mp3"] = [{
    text: "The Peasant and the Snake. A long time ago, a poor peasant and a snake were very good friends. The snake lived in a dark hole near the man's small house. Every morning, the peasant brought a fresh bowl of milk for the snake. In return, the snake brought a shiny gold coin for the man. One day, the peasant had to go on a long trip. He told his son, 'Please give milk to the snake every day.' But the son was very greedy. He thought, 'This snake must have a stomach full of gold coins! I will kill it and take all the money.' The next morning, the son tried to kill the snake with a heavy rock. He missed its head and only cut off its long tail. The snake was furious. It bit the son with its poisonous teeth, and the son died. When the sad father returned, he cried. He went to the hole and said, 'Let's be friends again.' The snake answered, 'No. While I have the pain of my lost tail, and you have the pain of your lost son, we can be friends at no point.'",
    dict: { "hole": "delik", "brought": "getirdi", "fresh": "taze", "bowl": "kase", "In return": "karşılığında", "shiny": "parlak", "coin": "madeni para", "trip": "yolculuk", "greedy": "açgözlü", "stomach": "mide", "full": "dolu", "rock": "kaya/taş", "missed": "ıskaladı", "cut off": "kesti/kopardı", "tail": "kuyruk", "furious": "öfkeli", "at no point": "hiçbir zaman/noktada" },
    questions: [ {q:"Were the peasant and the snake friends at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the snake give the man gold coins?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the peasant's son greedy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the son kill the snake?", a_en:"No", a_tr:"Hayır"}, {q:"Did the snake bite the son?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the son survive?", a_en:"No", a_tr:"Hayır"}, {q:"Could they be friends again at some point?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["46_ScorpionFrog.mp3"] = [{
    text: "The Scorpion and the Frog. A wildfire started in a forest. A scorpion and a frog reached a deep river. The scorpion said, 'Mr. Frog, please carry me on your back.' The frog said, 'No! You will sting me.' The scorpion laughed, 'If I sting you, we will both drown.' The frog agreed to help. In the middle of the river, the frog felt a sharp pain. The scorpion stung him! As they both started to sink, the dying frog cried, 'Why did you do it?' The scorpion answered, 'I am sorry. It is just my true nature.'",
    dict: { "wildfire": "orman yangını", "reached": "ulaştı", "deep": "derin", "carry": "taşımak", "sting": "sokmak", "drown": "boğulmak", "agreed": "kabul etti", "sharp": "keskin", "sink": "batmak", "nature": "doğa/fıtrat" },
    questions: [ {q:"Did the scorpion ask the frog for a ride?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the frog trust the scorpion at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did the scorpion sting the frog in the river?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they both start to sink?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the scorpion say it was his true nature?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the frog survive the sting?", a_en:"No", a_tr:"Hayır"}, {q:"Can a scorpion easily change its nature?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["47_ElephantNoise.mp3"] = [{
    text: "The Silent Elephant and the Noise. A group of monkeys often teased an old, silent elephant. 'Why are you so slow and stupid?' they laughed. The elephant gave no reply. One day, a huge storm arrived. The wind was so strong that it started to blow the monkeys out of the trees. The elephant walked into the middle of the wind and blocked the storm with his massive body. The monkeys hid behind him and were safe. When the storm finished, the elephant walked away without saying a word. He needed to speak at no point; his actions told the monkeys everything about strength.",
    dict: { "teased": "alay etti", "silent": "sessiz", "gave no reply": "cevap vermedi", "storm": "fırtına", "blow": "esmek/savurmak", "blocked": "engelledi", "massive": "devasa", "body": "vücut", "hid": "saklandılar", "behind": "arkasında", "at no point": "hiçbir zaman", "strength": "güç" },
    questions: [ {q:"Did the monkeys tease the silent elephant?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the elephant get angry and shout?", a_en:"No", a_tr:"Hayır"}, {q:"Did a huge storm arrive?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the elephant block the storm with his body?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the monkeys safe behind the elephant?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the elephant need to speak at some point?", a_en:"No", a_tr:"Hayır"}, {q:"Did his actions show his true strength?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["48_SnakeFile.mp3"] = [{
    text: "The Snake and the Steel File. A hungry snake slithered into a blacksmith's shop and bit a steel file. The steel was hard, and the snake's mouth started to bleed. But the snake was angry. It thought, 'I am making my enemy bleed!' So, the furious snake bit the steel harder and harder. The metal file was fine, but the snake destroyed its own mouth and died from its own blind anger.",
    dict: { "slithered": "süzüldü/kaydı", "blacksmith": "demirci", "shop": "dükkan", "steel file": "çelik eğe", "bleed": "kanamak", "furious": "öfkeli", "harder": "daha sert", "fine": "iyi/sağlam", "destroyed": "yok etti", "blind anger": "kör öfke" },
    questions: [ {q:"Did the snake bite a steel file?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the steel file soft?", a_en:"No", a_tr:"Hayır"}, {q:"Did the snake's mouth start to bleed?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the snake stop biting when it saw the blood?", a_en:"No", a_tr:"Hayır"}, {q:"Was the metal file destroyed?", a_en:"No", a_tr:"Hayır"}, {q:"Did the snake die from its own anger?", a_en:"Yes", a_tr:"Evet"}, {q:"Is attacking something stronger than you a smart idea?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["49_SpiderFly.mp3"] = [{
    text: "The Spider and the Flattered Fly. A clever spider invited a fly into his web. The fly was smart and said, 'No, everyone who goes in there dies.' The spider changed his plan. He said, 'You are so clever! And your wings are so shiny! You are the most beautiful bug in the world. I just want to look at your beauty.' The foolish fly loved the sweet compliments. She forgot the danger, flew closer to hear more nice words, and got stuck in the deadly web.",
    dict: { "web": "örümcek ağı", "everyone": "herkes", "dies": "ölür", "shiny": "parlak", "bug": "böcek", "look at": "bakmak", "beauty": "güzellik", "foolish": "aptalca", "compliments": "iltifatlar", "closer": "daha yakın", "stuck": "takılmış/sıkışmış", "deadly": "ölümcül" },
    questions: [ {q:"Did the spider invite the fly into his web?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fly say no at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the spider use sweet words to trick the fly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fly love the compliments?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fly remember the danger?", a_en:"No", a_tr:"Hayır"}, {q:"Did the fly get stuck in the web?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the spider's plan successful?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["50_TigerFox.mp3"] = [{
    text: "The Tiger and the Smart Fox. A hungry tiger caught a fox. The fox said, 'You cannot eat me! I am the magical King of this forest. Walk behind me, and I will prove it.' The tiger followed him. As they walked, all the smaller animals saw them and ran away in terror. The silly tiger thought the animals were running from the fox, but they were actually running from the tiger! The tiger quickly apologized and let the fox go free.",
    dict: { "caught": "yakaladı", "magical": "sihirli", "behind": "arkasında", "prove": "kanıtlamak", "followed": "takip etti", "terror": "dehşet", "actually": "aslında", "apologized": "özür diledi", "free": "özgür" },
    questions: [ {q:"Did the tiger catch a fox?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fox say he was the King of the forest?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the tiger walk behind the fox?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the small animals afraid of the fox?", a_en:"No", a_tr:"Hayır"}, {q:"Were the animals actually running from the tiger?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the tiger apologize?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the tiger eat the fox?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["51_TigerWoodpecker.mp3"] = [{
    text: "The Tiger and the Woodpecker. A tiger was eating when a bone got stuck in his teeth. He asked a woodpecker for help. 'If you pull the bone out, I will give you a big reward', said the tiger. The brave bird did it and successfully saved the tiger from the pain. Later, the bird asked for the reward. The cruel tiger laughed and said, 'You put your small head inside a hungry tiger's mouth, and I did not eat you. That is your reward! Now go away.'",
    dict: { "woodpecker": "ağaçkakan", "bone": "kemik", "stuck": "sıkışmış", "teeth": "dişler", "pull out": "çekip çıkarmak", "reward": "ödül", "successfully": "başarıyla", "pain": "acı", "cruel": "zalim", "inside": "içine" },
    questions: [ {q:"Did a bone get stuck in the tiger's teeth?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the tiger ask the bird for help?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bird pull the bone out?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the tiger give the bird a big bag of gold?", a_en:"No", a_tr:"Hayır"}, {q:"Was the tiger cruel?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the tiger eat the bird?", a_en:"No", a_tr:"Hayır"}, {q:"Was the tiger thankful?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["52_TurtleScorpion.mp3"] = [{
    text: "The Turtle and the Scorpion. A turtle and a scorpion were friends and needed to cross a river. The scorpion sat on the turtle's back. In the middle of the river, the turtle heard a scratching noise on his shell. The turtle asked, 'What are you doing?' The scorpion answered, 'I am trying to sting your shell. It is my nature.' The turtle realized his friend was dangerous. The turtle said, 'Well, it is my nature to dive under the water to protect myself.' He dived, and the scorpion washed away.",
    dict: { "cross": "geçmek/karşıya geçmek", "river": "nehir", "middle": "orta", "scratching": "tırmalama", "noise": "ses", "shell": "kabuk", "sting": "sokmak", "nature": "doğa/fıtrat", "dive": "dalmak", "washed away": "sürüklenip gitti" },
    questions: [ {q:"Were the turtle and scorpion friends?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the scorpion sit on the turtle's back?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the scorpion try to sting the turtle's shell?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the scorpion's nature to be kind?", a_en:"No", a_tr:"Hayır"}, {q:"Did the turtle dive under the water?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the scorpion washed away?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the turtle safe now?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["53_TurtleGeese.mp3"] = [{
    text: "The Turtle and the Two Geese. A friendly turtle talked way too much. Two geese offered to help him fly to a better lake. They said, 'Bite the middle of this stick, and we will fly. But you must keep your mouth shut!' The turtle bit the stick, and they flew into the sky. People on the ground saw them and shouted, 'Look at the funny flying turtle!' The proud turtle became angry. He opened his mouth to shout, 'Be quiet!' but he immediately fell to the ground and died.",
    dict: { "friendly": "arkadaş canlısı", "geese": "kazlar", "fly": "uçmak", "bite": "ısırmak", "stick": "sopa/çubuk", "shut": "kapalı", "immediately": "derhal", "fell": "düştü" },
    questions: [ {q:"Did the turtle talk too much?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the geese help the turtle fly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the turtle have to keep his mouth shut?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people laugh at the flying turtle?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the turtle stay quiet?", a_en:"No", a_tr:"Hayır"}, {q:"Did the turtle open his mouth?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the turtle fall to the ground?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["54_TwoDogs.mp3"] = [{
    text: "The Two Dogs. A grandfather was watching İki dogs in the yard. One was black, and the other was white. They were fighting each other loudly. The grandfather explained to his grandson, 'The white dog represents all our good feelings: love and kindness. The black dog represents our bad feelings: anger and hate. These İki sides are always fighting inside our hearts.' The little boy asked, 'Which dog is going to win?' The old man answered, 'The one that I feed better will win.'",
    dict: { "grandfather": "büyükbaba", "watching": "izliyor", "yard": "bahçe/avlu", "fighting": "savaşıyor/dövüşüyor", "explained": "açıkladı", "grandson": "erkek torun", "represents": "temsil eder", "kindness": "iyilik/nezaket", "hearts": "kalpler", "feed": "beslemek" },
    questions: [ {q:"Were there two dogs fighting in the yard?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the white dog represent bad feelings?", a_en:"No", a_tr:"Hayır"}, {q:"Does the black dog represent anger and hate?", a_en:"Yes", a_tr:"Evet"}, {q:"Are these sides fighting inside our hearts?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the boy ask which dog will win?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the dog we feed better win?", a_en:"Yes", a_tr:"Evet"}, {q:"Should we feed our bad feelings more?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["55_TwoFrogsMilk.mp3"] = [{
    text: "The Two Frogs and the Milk. Two frogs fell into a bucket of milk. The first frog became hopeless. He cried, 'This is impossible!' He stopped swimming and drowned. The second frog gave up at no point. He kicked his legs and swam in circles for hours. Because of his movement, the milk began to change. The cream turned into solid butter! Soon, the frog was standing on a hard piece of butter. He used the solid surface to jump out of the bucket and was safe.",
    dict: { "bucket": "kova", "hopeless": "umutsuz", "impossible": "imkansız", "drowned": "boğuldu", "at no point": "hiçbir zaman", "kicked": "tekmeledi/vurdu", "movement": "hareket", "cream": "krema", "solid": "katı", "butter": "tereyağı", "surface": "yüzey", "safe": "güvenli" },
    questions: [ {q:"Did two frogs fall into a bucket of milk?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the first frog keep swimming?", a_en:"No", a_tr:"Hayır"}, {q:"Did the second frog give up at any point?", a_en:"No", a_tr:"Hayır"}, {q:"Did the milk turn into butter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the second frog stand on the butter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the second frog drown?", a_en:"No", a_tr:"Hayır"}, {q:"Was the second frog safe at the end?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["56_RoostersEagle.mp3"] = [{
    text: "The Two Roosters and the Eagle. Two roosters lived on a farm and fought for the farmyard. The winner, full of pride, flew to the top of a stone wall. He flapped his wings and crowed loudly to tell everyone about his great victory. However, a hungry eagle heard the loud crowing and saw the boastful rooster standing alone on the wall. In a second, the eagle dropped like a stone, grabbed the winner in his sharp claws, and carried him away to be eaten. The rooster who had lost the fight came out of his dark corner and became the master of the farmyard.",
    dict: { "roosters": "horozlar", "farmyard": "çiftlik avlusu", "pride": "gurur", "stone wall": "taş duvar", "flapped": "çırptı", "crowed": "öttü", "victory": "zafer", "boastful": "böbürlenen", "grabbed": "yakaladı", "claws": "pençeler", "master": "efendi/usta" },
    questions: [ {q:"Did two roosters fight on a farm?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the winner fly to the top of a wall?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the winner very humble?", a_en:"No", a_tr:"Hayır"}, {q:"Did an eagle hear the rooster crowing?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the eagle grab the winner?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the losing rooster become the new master?", a_en:"Yes", a_tr:"Evet"}, {q:"Is too much pride dangerous?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["57_TwoSeeds.mp3"] = [{
    text: "The Two Seeds. Two small seeds lay side by side in the dark earth during the early spring. The first seed was very brave. 'I want to grow!' she said. 'I want to push my roots deep and see the beautiful world above the soil. I want to feel the warm sun on my face and bloom.' The second seed was very shy and cautious. 'I am afraid,' he replied. 'If I push my head into the air, a big bird might eat me. If I grow a flower, someone might pull me out of the ground. It is much safer to stay here in the dark where it is quiet.' The first seed pushed through the dirt. Soon, she became a tall, strong plant with many green leaves. Meanwhile, the second seed stayed hidden under the soil, waiting for a safe time that came at no point. One afternoon, a hungry chicken walked through the garden. The sun was hot, so the chicken stopped to rest in the shadow of the tall plant. While sitting there, the chicken scratched the dirt. It found the cautious seed and ate it for lunch.",
    dict: { "seeds": "tohumlar", "earth": "toprak", "brave": "cesur", "roots": "kökler", "soil": "toprak", "bloom": "çiçek açmak", "shy": "utangaç", "cautious": "temkinli/dikkatli", "replied": "cevap verdi", "at no point": "hiçbir zaman/noktada", "shadow": "gölge", "scratched": "eşeledi/tırmaladı" },
    questions: [ {q:"Did the first seed want to grow?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the second seed brave?", a_en:"No", a_tr:"Hayır"}, {q:"Did the first seed become a tall plant?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the second seed stay hidden under the soil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the safe time ever come for the second seed?", a_en:"No", a_tr:"Hayır"}, {q:"Did a chicken eat the cautious seed?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it safer to do nothing at all?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["58_WarriorWolf.mp3"] = [{
    text: "The Warrior and the Loyal Wolf. A brave warrior found an orphaned wolf cub and raised it as his best friend. Despite the tribe's warnings, the animal grew up very loyal. One day, the warrior had to leave his newborn baby alone and left the wolf to guard the tipi. When he returned, he saw the wolf outside with blood on its mouth and the baby's cradle pushed over. In a fit of rage, the warrior grabbed his gun and shot the wolf. As the wolf died, the warrior heard his baby crying. He ran inside and saw his child sleeping safely on the floor. Next to the cradle lay a massive, dead puma. The wolf had fought the predator to save the baby's life. The warrior cried as he realized he had killed his most loyal protector.",
    dict: { "warrior": "savaşçı", "wolf cub": "kurt yavrusu", "raised": "büyüttü", "Despite": "rağmen", "tribe": "kabile", "newborn": "yeni doğmuş", "tipi": "çadır/tepee", "cradle": "beşik", "gun": "silah", "puma": "puma/dağ aslanı", "predator": "yırtıcı", "protector": "koruyucu" },
    questions: [ {q:"Did the warrior raise an orphaned wolf?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the wolf loyal?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the warrior find blood on the wolf's mouth?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the warrior kill the wolf in a fit of rage?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the wolf kill the baby?", a_en:"No", a_tr:"Hayır"}, {q:"Was there a dead puma next to the cradle?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the wolf save the baby's life?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["59_WolfLamb.mp3"] = [{
    text: "The Wolf and the Lamb. A hungry wolf saw a small lamb drinking water at a stream. The wolf shouted, 'How dare you make my water dirty?' The lamb trembled and said, 'Sir, I am drinking downstream from you. I can make your water dirty at no point.' The wolf was angry because the lamb was right. He tried another lie. 'Last year, you said terrible things about my father!' The lamb cried, 'Sir, I was even born at no point last year!' Finally, the wolf hissed, 'I care nothing about your logic. I am hungry, and you are dinner.' He jumped on the lamb and ate him.",
    dict: { "lamb": "kuzu", "stream": "dere", "How dare you": "nasıl cüret edersin", "trembled": "titredi", "downstream": "akıntı yönünde", "at no point": "hiçbir zaman/noktada", "lie": "yalan", "hissed": "tısladı", "care nothing": "hiç önemsememek", "logic": "mantık" },
    questions: [ {q:"Was the wolf hungry?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lamb make the water dirty?", a_en:"No", a_tr:"Hayır"}, {q:"Was the lamb drinking downstream?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the lamb speak badly about the wolf's father last year?", a_en:"No", a_tr:"Hayır"}, {q:"Was the lamb even born last year?", a_en:"No", a_tr:"Hayır"}, {q:"Did the wolf care about logic?", a_en:"No", a_tr:"Hayır"}, {q:"Did the wolf eat the lamb?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["60_WolfSheep.mp3"] = [{
    text: "The Wolf in Sheep’s Clothing. A hungry, clever wolf could catch no sheep because the smart shepherd watched the flock closely. One day, the wolf found a sheep’s skin and put it over his own body. He walked into the group of sheep. The busy shepherd thought he was a real sheep and locked him securely in the pen for the night. The wolf planned to eat a fat sheep in the dark. But that night, the shepherd suddenly wanted fresh meat for his own dinner. He went into the dark pen, grabbed the first 'sheep' he saw, and killed it. It was the disguised wolf.",
    dict: { "clothing": "giysi", "shepherd": "çoban", "flock": "sürü", "skin": "deri", "securely": "güvenli bir şekilde", "pen": "ağıl", "dark": "karanlık", "meat": "et", "disguised": "kılık değiştirmiş" },
    questions: [ {q:"Could the wolf catch any sheep at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did the wolf wear a sheep's skin?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the shepherd think the wolf was a real sheep?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the wolf locked in the pen?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the wolf eat a fat sheep that night?", a_en:"No", a_tr:"Hayır"}, {q:"Did the shepherd kill the disguised wolf for dinner?", a_en:"Yes", a_tr:"Evet"}, {q:"Is pretending to be someone else safe?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["61_WoodcutterTrees.mp3"] = [{
    text: "The Woodcutter and the Trees. A poor woodcutter went deep into the quiet forest. He had an axe head, but he had a wooden handle for it at no level. He politely asked the trees, 'Please, give me just a small piece of strong wood to make a handle for my tool.' The kind trees felt sorry for the man. They gave him a nice, strong piece of ash wood. The woodcutter quickly fixed his axe. Then, he immediately started swinging his sharp axe to cut down all the beautiful trees in the forest. The generous trees realized their terrible mistake far too late.",
    dict: { "woodcutter": "oduncu", "axe head": "balta başı", "handle": "sap", "at no level": "hiç/yok", "tool": "araç/alet", "ash wood": "dişbudak ağacı", "fixed": "tamir etti", "swinging": "sallıyor", "sharp": "keskin", "cut down": "kesmek/devirmek", "generous": "cömert" },
    questions: [ {q:"Did the woodcutter have an axe handle at the start?", a_en:"No", a_tr:"Hayır"}, {q:"Did he ask the trees for a piece of wood?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the trees kind and generous?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the trees give him a piece of ash wood?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the woodcutter fix his axe?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the woodcutter protect the trees?", a_en:"No", a_tr:"Hayır"}, {q:"Did the woodcutter cut down the beautiful trees?", a_en:"Yes", a_tr:"Evet"} ]
}];
